#+TITLE: Emacs key bindings for Lisp programming
#+DATE: 2012-02-23
#+TAGS: emacs-lisp clojure

I finished reading
[[http://www.amazon.com/gp/product/0596006489/ref=as_li_ss_tl?ie=UTF8&tag=comprhegel-20&linkCode=as2&camp=1789&creative=390957&creativeASIN=0596006489][Learning
GNU Emacs, Third Edition]] this
week. The edition is from 2004 but the book has aged well. All essential
concepts, modes and key bindings are presented. The Emacs documentation
system is also explained, which is useful to know if you want to further
extend your knowledge once you read the book. One chapter is an
introduction to Emacs programming with Emacs Lisp. It gives the basis to
start and explains how to implement a simple major mode. Of course since
2004, the Emacs ecosystem has changed so you won't find something on
[[http://www.emacswiki.org/emacs/Magit][Magit]] mode (for Git) or on the
[[http://tromey.com/elpa/][Emacs Lisp Package Archive]] but if you are
not an expert Emacs user, you will learn from reading it.

One chapter is on programming modes and Lisp key bindings are presented.
Even if you don't use
[[http://www.emacswiki.org/emacs/ParEdit][paredit]] (and really you
should - just take a few minutes to learn its key binding) many commands
are available to work with S-expressions. Here is one table of the book
that illustrates them: ...image lost due to rot link....

Structurally editing S-expressions gives an intense satisfaction and
will make you regret Lisp syntax whenever you have to program with an
another language family.
