#+TITLE: Linux distributions as a service
#+DATE: 2013-09-28
#+TAGS: linux

One of my colleague installed Ubuntu on his Mac computers and was
surprised by the varieties of Ubuntu distributions offered. There are
different distributions and differents architectures and he was
wondering how they managed this complexity.

This gave me an idea. What about having even more distributions? What
about having _personalized distribution customized for your
particular machine_ ?

A usage scenario could be like this:

- you go on the website of a Linux distribution,
- start an application that analyze your hardware,
- answer a few questions about your requirements (security, network,
  etc),
- choose the graphical environment, choose or customize some graphical
  themes (for a desktop distribution) etc.
- you then get a link where you could download your own customized
  distribution, tailored for your needs and hardware. Or maybe you enter
  an email and you get a link via email when the build is finished.

Common choices and typical hardware configurations could be shared by
the community.

It would require a good infrastructure but it could be a service people
would be ready to pay for.

Currently only expert Linux users can tailor their distributions for
their needs, Linux distributions as a service (or "on demand") could
bring more power and more control to a broader public.
