#+TITLE: An Emacs minor mode to mute email threads
#+DATE: 2014-01-17
#+TAGS: emacs email

Emacs is best know to be a powerful text editor. It is also a powerful note
editing system with [[http://orgmode.org/][org-mode]]. Since emails are mostly composed of text it also
makes sense to use Emacs for reading and writing them ; automating
common tasks is possible with Emacs Lisp and taking notes and referencing
emails within org-mode is easy.

To read my emails with Emacs I use the [[http://notmuchmail.org/][notmuch]] program. It indexes emails very
quickly and functions with tags. Searching is super fast, even with a
huge number of emails.

Since Emacs is almost infinitely customizable, I hacked a minor mode for notmuch
that allow me to mute email threads. You can mark a thread of emails as 'killed'
and all incoming email belonging to this thread will be automatically marked as
read upon arrival.

The mode is not very efficient for the moment but you are encouraged to try it
on your own and see if it improves your workflow.

You can [[https://github.com/kototama/notmuch-kill-mode][find the mode on GitHub]]. Happy hacking!
